package System;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Yo200
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    MainMenu MM;
    public SignUp(MainMenu M) {
        MM = M;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SignUpSignUpLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        SignUpInputUsername = new javax.swing.JTextField();
        SignUpUsernameLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        SignUpPasswordLabel = new javax.swing.JLabel();
        SignUpInputPassword = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        SignUpConfirmPasswordLabel = new javax.swing.JLabel();
        SignUpInputConfirmPassword = new javax.swing.JPasswordField();
        jPanel20 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        SignUpInputName = new javax.swing.JTextField();
        SignUpNameLabel = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        SignUpInputPhoneNum = new javax.swing.JTextField();
        SignUpPhoneNumLabel = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        SignUpInputEmail = new javax.swing.JTextField();
        SignUpEmailLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        SignUpCreateAccountButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        SignUpAccountExistsLabel = new javax.swing.JLabel();
        SignUpLoginButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 706, 516));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 512));

        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 516));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 35));

        SignUpSignUpLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpSignUpLabel.setText("Sign Up");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(SignUpSignUpLabel)
                .addGap(164, 164, 164))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpSignUpLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel7.setMinimumSize(new java.awt.Dimension(410, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 340));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 375));

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel5.setLayout(new java.awt.BorderLayout(5, 5));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel19.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel19.setLayout(new java.awt.BorderLayout(5, 5));

        SignUpInputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInputUsernameActionPerformed(evt);
            }
        });
        jPanel19.add(SignUpInputUsername, java.awt.BorderLayout.CENTER);

        SignUpUsernameLabel.setText("Username");
        jPanel19.add(SignUpUsernameLabel, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel5);

        jPanel11.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel11.setLayout(new java.awt.BorderLayout(5, 5));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField4, java.awt.BorderLayout.CENTER);

        jPanel18.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel18.setLayout(new java.awt.BorderLayout(5, 5));

        SignUpPasswordLabel.setText("Password");
        jPanel18.add(SignUpPasswordLabel, java.awt.BorderLayout.PAGE_START);

        SignUpInputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInputPasswordActionPerformed(evt);
            }
        });
        jPanel18.add(SignUpInputPassword, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel18, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel11);

        jPanel8.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel8.setLayout(new java.awt.BorderLayout(5, 5));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField3, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel9.setLayout(new java.awt.BorderLayout(5, 5));

        SignUpConfirmPasswordLabel.setText("Confirm Password");
        jPanel9.add(SignUpConfirmPasswordLabel, java.awt.BorderLayout.PAGE_START);

        SignUpInputConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInputConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel9.add(SignUpInputConfirmPassword, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel8);

        jPanel20.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel20.setLayout(new java.awt.BorderLayout(5, 5));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField6, java.awt.BorderLayout.CENTER);

        jPanel21.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel21.setLayout(new java.awt.BorderLayout(5, 5));

        SignUpInputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInputNameActionPerformed(evt);
            }
        });
        jPanel21.add(SignUpInputName, java.awt.BorderLayout.CENTER);

        SignUpNameLabel.setText("Name");
        jPanel21.add(SignUpNameLabel, java.awt.BorderLayout.PAGE_START);

        jPanel20.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel20);

        jPanel22.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel22.setLayout(new java.awt.BorderLayout(5, 5));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel22.add(jTextField8, java.awt.BorderLayout.CENTER);

        jPanel23.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel23.setLayout(new java.awt.BorderLayout(5, 5));

        SignUpInputPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInputPhoneNumActionPerformed(evt);
            }
        });
        jPanel23.add(SignUpInputPhoneNum, java.awt.BorderLayout.CENTER);

        SignUpPhoneNumLabel.setText("Phone Number");
        jPanel23.add(SignUpPhoneNumLabel, java.awt.BorderLayout.PAGE_START);

        jPanel22.add(jPanel23, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel22);

        jPanel24.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel24.setLayout(new java.awt.BorderLayout(5, 5));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel24.add(jTextField10, java.awt.BorderLayout.CENTER);

        jPanel25.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel25.setLayout(new java.awt.BorderLayout(5, 5));

        SignUpInputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInputEmailActionPerformed(evt);
            }
        });
        jPanel25.add(SignUpInputEmail, java.awt.BorderLayout.CENTER);

        SignUpEmailLabel.setText("E-mail Address");
        jPanel25.add(SignUpEmailLabel, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel25, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel24);

        jPanel7.add(jPanel4);

        jPanel1.add(jPanel7);

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel12.setPreferredSize(new java.awt.Dimension(400, 50));

        SignUpCreateAccountButton.setBackground(new java.awt.Color(79, 220, 83));
        SignUpCreateAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUpCreateAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpCreateAccountButton.setText("CREATE ACCOUNT");
        SignUpCreateAccountButton.setActionCommand("Login");
        SignUpCreateAccountButton.setPreferredSize(new java.awt.Dimension(300, 29));
        SignUpCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpCreateAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(SignUpCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12);

        jPanel13.setPreferredSize(new java.awt.Dimension(400, 75));

        SignUpAccountExistsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpAccountExistsLabel.setText("Already have an account?");
        SignUpAccountExistsLabel.setPreferredSize(new java.awt.Dimension(300, 16));

        SignUpLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUpLoginButton.setText("LOGIN");
        SignUpLoginButton.setPreferredSize(new java.awt.Dimension(300, 29));
        SignUpLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignUpAccountExistsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SignUpLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpAccountExistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel13);

        jPanel1.add(jPanel10);

        jPanel2.setBackground(new java.awt.Color(66, 128, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 516));

        jPanel14.setBackground(new java.awt.Color(39, 94, 242));
        jPanel14.setPreferredSize(new java.awt.Dimension(300, 258));

        jPanel15.setBackground(new java.awt.Color(0, 28, 209));
        jPanel15.setPreferredSize(new java.awt.Dimension(300, 128));

        jPanel16.setBackground(new java.awt.Color(0, 7, 105));

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 130, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void SignUpCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpCreateAccountButtonActionPerformed
        // TODO add your handling code here:
        //AccountMade
        MM.setVisible(true);
    }//GEN-LAST:event_SignUpCreateAccountButtonActionPerformed

    private void SignUpInputConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInputConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpInputConfirmPasswordActionPerformed

    private void SignUpLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpLoginButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        (new Login(MM)).setVisible(true);
    }//GEN-LAST:event_SignUpLoginButtonActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void SignUpInputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpInputPasswordActionPerformed

    private void SignUpInputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpInputUsernameActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void SignUpInputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpInputNameActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void SignUpInputPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInputPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpInputPhoneNumActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void SignUpInputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpInputEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignUpAccountExistsLabel;
    private javax.swing.JLabel SignUpConfirmPasswordLabel;
    private javax.swing.JButton SignUpCreateAccountButton;
    private javax.swing.JLabel SignUpEmailLabel;
    private javax.swing.JPasswordField SignUpInputConfirmPassword;
    private javax.swing.JTextField SignUpInputEmail;
    private javax.swing.JTextField SignUpInputName;
    private javax.swing.JPasswordField SignUpInputPassword;
    private javax.swing.JTextField SignUpInputPhoneNum;
    private javax.swing.JTextField SignUpInputUsername;
    private javax.swing.JButton SignUpLoginButton;
    private javax.swing.JLabel SignUpNameLabel;
    private javax.swing.JLabel SignUpPasswordLabel;
    private javax.swing.JLabel SignUpPhoneNumLabel;
    private javax.swing.JLabel SignUpSignUpLabel;
    private javax.swing.JLabel SignUpUsernameLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
